spring:
  datasource:
    url: jdbc:mysql://60.205.226.163:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml